### ISSUE TITLE
Size of the output

### ISSUE THREAD

**Issue by ValorNaram** [giggls/osmpoidb#2]
How big is your database after running the code?

I assume you have downloaded the whole planet file, extracted it and only merged data you need into a dababase.

**Comment by giggls** [comment]
Size of /var/lib/postgresql on everest.openstreetmap.de, the FOSSGIS dev-server, is currently 14GB for the whole Planet updated once an per hour. If you want to use this I can provide a shell-account.

https://wiki.openstreetmap.org/wiki/FOSSGIS/Server/Development-Server

**Comment by ValorNaram** [comment]
Thank you for fast reply.

Background: I search for a database hoster for [Babykarte](https://github.com/babykarte/babykarte.github.io/) and that's why I asked which size your database has. Just for getting an overview. I am currently checking all possibilities because Babykarte should remain ad-free.

**Comment by giggls** [comment]
Talking about hosting will make this off-topic here. Please contact me via Email if you want to know more about FOSSGIS dev-server. Unfortunately the documentation on OSM Wiki is a bit outdated.
